{:npm-deps {"leaflet" "^1.6.0"
            "react-leaflet" "^2.6.0"
            "ag-grid-community" "^22.0.0"
            "ag-grid-react" "^22.0.0"
            "react-dom-factories" "^1.0.2"
            "react-sparklines" "^1.7.0"
            "react-player" "^1.14.2"
            "vega" "^5.11.1"
            "vega-embed" "^6.7.0"
            "vega-lite" "^4.11.0"
            "highcharts" "^8.0.4"
            "tailwindcss" "^1.4.6"
            "react-grid-layout" "^0.18.3"}}
